[package]
name = "stranger"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
tui-textarea = "0.7.0"
crossterm = { version = "0.27", features = ["event-stream"] }
tokio = { version = "1.40", features = ["full"] }
open = "5.3"

[dev-dependencies]
tempfile = "3.20.0"
